#!/usr/bin/env python3
"""GE19 H4F2g source-only audit of six-piece signed Ward ledger.

Deterministic source-array tests use the actual Stage E Y source_h4 and
the original Repair37 M1 mapped source. The other four external non-Y
families are explicitly marked synthetic stand-ins; their action-source
definitions have already passed the individually frozen H4F2a-f audits.
No corrected-parent arrays, full Noether residual or H4/Z21 solver run.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from ge19 import h4f2g_action_completed_six_piece_source_ledger as ledger
from ge19 import h4_stagee_versioned_y_source_rows as stagee
from ge19 import repair07_window_retarded_reduced_h3_z20_particular as r7
from ge19 import repair37_cancellation_safe_fd8_h4_z21_reclosure as r37

def relative(a,b):
    x=np.asarray(a)
    y=np.asarray(b)
    return float(np.linalg.norm(x-y)/max(
        np.linalg.norm(x),np.linalg.norm(y),1e-300
    ))

def synthetic_external(a,Q,kfund,beta_index,nt,nm):
    ext={}
    tt=np.arange(nt,dtype=float)[:,None]
    mm=np.arange(nm,dtype=float)[None,:]
    for ip,name in enumerate(ledger.NON_Y):
        main=np.zeros((6,nt,nm),complex)
        con=np.zeros((2,nt,nm),complex)
        for i in ledger.SUPPORT[name]:
            if name=="2M1_GE05_mapped":
                continue
            phase=(i+1)*0.171+(ip+1)*0.131+tt*0.23+mm*0.037
            source=(1e-7/(ip+1))*(i+1)*(
                np.cos(phase)+1j*np.sin(phase)
            )
            source[:,0]=source[:,0].real
            if i<6:
                main[i]=source
            else:
                con[i-6]=source
        ext[name]=(main,con)
    # M1 MUST be generated by the actual frozen Repair37 implementation,
    # including its original GE05->GE06 factor two and B20 projection.
    b=np.arange(3,dtype=float)[:,None,None]
    m=np.arange(1,41,dtype=float)[None,:,None]
    it=np.arange(nt,dtype=float)[None,None,:]
    B=1e-9*(np.cos(m/7.0+it/9.0+b*0.27)
             +1j*np.sin(m/8.0-it/11.0+b*0.13))
    m1,con=r37.m1_mapped_fourier(
        {"a":a,"Q_action":Q},B
    )
    ext["2M1_GE05_mapped"]=(m1[beta_index],con[beta_index])
    return ext

def verify_invalid(ext,params):
    errs={}
    def rejected(which,x,p):
        try:
            ledger.assemble_six(x,**p)
        except (ValueError,FloatingPointError):
            errs[which]=True
        else:
            errs[which]=False
    bad=dict(ext)
    bad["2DY2"]=bad["2M1_GE05_mapped"]
    rejected("legacy_scalar_only_Y_addition_rejected",bad,params)
    bad=dict(ext);del bad["2M2_GE05_mapped"]
    rejected("missing_M2_family_rejected",bad,params)
    bad=dict(ext)
    g=np.array(bad["2Q_GE07_cross"][1],copy=True)
    bad["2Q_GE07_cross"]=(bad["2Q_GE07_cross"][0],g[:1])
    rejected("missing_GE07_shift_constraint_row_rejected",bad,params)
    bad=dict(ext)
    g=np.array(bad["2Q_Lambda_cross"][1],copy=True)
    g[0,0,2]=1e-3
    bad["2Q_Lambda_cross"]=(bad["2Q_Lambda_cross"][0],g)
    rejected("forbidden_Lambda_shift_rejected",bad,params)
    bad=dict(ext)
    g=np.array(bad["2Q_GE06_cross"][0],copy=True)
    g[3,0,1]=np.nan
    bad["2Q_GE06_cross"]=(g,bad["2Q_GE06_cross"][1])
    rejected("nonfinite_external_source_rejected",bad,params)
    wrong=dict(params)
    wrong["time"]=np.zeros_like(params["time"])
    rejected("nonmonotonic_common_grid_rejected",ext,wrong)
    wrong=dict(params)
    wrong["beta"]=0.2
    rejected("unfrozen_beta_rejected",ext,wrong)
    return errs

def run_case(beta,ib):
    nt,nx,mmax=5,256,40
    time=np.linspace(-0.88,-0.57,nt)
    a=0.56+0.042*np.arange(nt,dtype=float)
    Q=1.0e-4+1.7e-6*np.arange(nt,dtype=float)
    t=np.arange(nt,dtype=float)[:,None]
    x=2*np.pi*np.arange(nx,dtype=float)[None,:]/nx
    u0=1e-4*np.cos(x+0.12*t)+3e-5*np.sin(3*x-0.07*t)
    u1=8e-5*np.cos(2*x-0.21*t)+2e-5*np.sin(4*x+0.11*t)
    g0=1.1e-7*np.sin(x+0.08*t)+2.1e-8*np.cos(5*x-0.13*t)
    g1=4.2e-8*np.cos(2*x+0.1*t)+1.2e-8*np.sin(6*x-0.09*t)
    px0=a[:,None]*(g0-Q[:,None]*u0)
    px1=a[:,None]*(g1-Q[:,None]*u1)
    kfund=float(r7.g9.K_REQ[0]/r7.FOURIER_N[0])
    ext=synthetic_external(a,Q,kfund,ib,nt,mmax+1)
    saved={k:(np.array(v[0],copy=True),np.array(v[1],copy=True))
           for k,v in ext.items()}
    params={
        "a":a,"Q":Q,"u10":u0,"phi10_x":px0,
        "u11":u1,"phi11_x":px1,
        "KB":r7.KB,"a0":r7.A0_MPC_INV,"beta":beta,
        "kfund":kfund,"time":time,"mmax":mmax,
    }
    ans=ledger.assemble_six(ext,**params)
    ny=stagee.source_h4(
        a,Q,u0,px0,u1,px1,r7.KB,r7.A0_MPC_INV,
        beta,kfund
    )
    direct_y=np.concatenate((
        np.fft.fft(ny["main"],axis=-1)[:,:,:mmax+1]/nx,
        np.fft.fft(ny["constraint"],axis=-1)[:,:,:mmax+1]/nx,
    ),axis=0)
    expected=sum(
        (np.concatenate(saved[k],axis=0) for k in ledger.NON_Y),
        np.array(direct_y,copy=True)
    )
    actual=ans["total_rows"]
    ward_parts=sum(
        (ans["source_ward_by_piece"][k] for k in ledger.PIECES),
        np.zeros_like(ans["total_source_ward"])
    )
    numeric={
        "beta":beta,
        "new_Y_both_rows_exact":
            bool(np.array_equal(ans["piece_rows"][ledger.Y_PIECE],direct_y)),
        "new_Y_aether_nonzero":bool(np.linalg.norm(direct_y[2])>0),
        "new_Y_scalar_nonzero":bool(np.linalg.norm(direct_y[3])>0),
        "new_Y_all_forbidden_rows_zero":
            bool(np.array_equal(direct_y[[0,1,4,5,6,7]],
                                np.zeros((6,nt,mmax+1)))),
        "external_families_preserved_bitwise":bool(
            all(np.array_equal(ext[k][j],saved[k][j])
                for k in ledger.NON_Y for j in (0,1))
        ),
        "six_piece_sum_relative_L2":relative(expected,actual),
        "signed_ward_piece_sum_relative_L2":
            relative(ward_parts,ans["total_source_ward"]),
        "Y_source_ward_exact_zero":
            bool(np.array_equal(ans["source_ward_by_piece"][ledger.Y_PIECE],
                                np.zeros((nt,mmax+1)))),
        "M1_source_ward_exact_zero":
            bool(np.array_equal(ans["source_ward_by_piece"]["2M1_GE05_mapped"],
                                np.zeros((nt,mmax+1)))),
        "Lambda_direct_shift_exact_zero":
            bool(np.array_equal(ans["piece_rows"]["2Q_Lambda_cross"][6],
                                np.zeros((nt,mmax+1)))),
        "Lambda_source_ward_nonzero":
            bool(np.linalg.norm(ans["source_ward_by_piece"]["2Q_Lambda_cross"])>0),
        "GE07_shift_preserved_nonzero":
            bool(np.linalg.norm(ans["piece_rows"]["2Q_GE07_cross"][6])>0),
        "M2_anisotropy_preserved_nonzero":
            bool(np.linalg.norm(ans["piece_rows"]["2M2_GE05_mapped"][7])>0),
        "total_source_ward_not_assumed_zero":
            bool(np.linalg.norm(ans["total_source_ward"])>0),
        "finite_all_results":bool(
            all(np.isfinite(p).all() for p in
                list(ans["piece_rows"].values())
                +list(ans["source_ward_by_piece"].values())
                +[actual,ans["total_source_ward"]])
        ),
        "corrected_parent_and_operator_Ward_not_evaluated":bool(
            ans["full_six_piece_parent_Noether_certified"] is False
            and ans["linear_operator_Ward_evaluated"] is False
            and ans["background_H1_Z11_Z20_q20_dust_bath_parent_residuals_evaluated"] is False
            and ans["Z21_solved"] is False
        ),
    }
    numeric["invalid_cases_rejected"]=verify_invalid(ext,params)
    # Deliberate factor-nx perturbation must be detected against the
    # independent synthetic reference. The bare-array assembly API does
    # not authenticate external generator provenance.
    wrong=dict(ext)
    m,c=wrong["2Q_GE06_cross"]
    wrong["2Q_GE06_cross"]=(nx*m,nx*c)
    amplified=ledger.assemble_six(wrong,**params)
    numeric["wrong_fft_amplitude_visible_vs_reference"]=bool(
        relative(expected,amplified["total_rows"])>1e-3
    )
    numeric["all_numeric_gates_pass"]=bool(
        all(v for k,v in numeric.items()
            if k not in ("beta","six_piece_sum_relative_L2",
                         "signed_ward_piece_sum_relative_L2",
                         "invalid_cases_rejected","all_numeric_gates_pass"))
        and all(numeric["invalid_cases_rejected"].values())
        and numeric["six_piece_sum_relative_L2"]<=1e-13
        and numeric["signed_ward_piece_sum_relative_L2"]<=1e-13
    )
    return numeric

def main():
    p=argparse.ArgumentParser()
    p.add_argument("--json-out",required=True)
    args=p.parse_args()
    blobs=ledger.exact_blobs()
    bindings=ledger.frozen_source_bindings()
    cases=[run_case(beta,i)
           for i,beta in enumerate(stagee.FROZEN_BETAS)]
    ok=bool(all(v["exact"] for v in blobs.values())
            and all(bindings.values())
            and all(t["all_numeric_gates_pass"] for t in cases))
    report={
        "classification":(
            "GE19_H4F2G_SIGNED_SIX_PIECE_SOURCE_LEDGER_PASS_FULL_NOETHER_OPEN"
            if ok else
            "GE19_H4F2G_SIX_PIECE_SOURCE_LEDGER_FAIL"
        ),
        "preregistration":
            "GE19_H4F2G_PREDATA_ACTION_COMPLETED_SIX_PIECE_SOURCE_WARD_LEDGER",
        "frozen_blobs":blobs,
        "frozen_implementation_bindings":bindings,
        "six_piece_order":ledger.PIECES,
        "source_row_order":ledger.GE19_ROWS,
        "source_row_support":{k:list(v)
                              for k,v in ledger.SUPPORT.items()},
        "source_only_beta_cases":cases,
        "all_source_ledger_gates_pass":ok,
        "external_GE06_GE07_Lambda_M2_arrays_are_synthetic_controls":True,
        "actual_GE05_M1_generator_used":True,
        "actual_StageE_Y_H4_source_generator_used":True,
        "actual_corrected_H3F_H3G_and_Z11_parent_arrays_used":False,
        "external_source_amplitudes_authenticated_on_corrected_parents":False,
        "full_six_piece_parent_operator_Noether_derived":False,
        "common_corrected_parent_source_evaluated":False,
        "H4_Z21_solve_performed":False,
        "Z21_certified":False,
        "lensing_licensed":False,
        "next_route":(
            "PREREGISTER_CORRECTED_PARENT_COMMON_TIME_SIGNED_FULL_WARD_RESIDUAL_AUDIT"
            if ok else "FREEZE_AND_LOCALIZE_SIGNED_SOURCE_LEDGER_FAILURE"
        ),
        "claim_boundary":
          "Valid standalone six-piece source bookkeeping and signed source Ward projection only. Synthetic external families do not certify their physical amplitudes on corrected parents. The full all-sector continuum/discrete Noether identity, parent and linear-operator Ward defects, common time/source representation and H4/Z21 science remain open."
    }
    dest=Path(args.json_out)
    dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text(json.dumps(report,indent=2,sort_keys=True,allow_nan=False)+"\n")
    print(json.dumps(report,indent=2,sort_keys=True,allow_nan=False))
    if not ok:
        raise SystemExit(3)

if __name__=="__main__":
    main()
