#!/usr/bin/env python3
from __future__ import annotations

import ast
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
C6 = ROOT / 'nl1c6' / 'spherical_self_gravity_g1_g10.py'
G11 = ROOT / 'nl1c6' / 'g11_solver_readiness.py'
OUT = ROOT / 'results' / 'nl1c7b_matter_backreaction_closure_audit.json'

EXPECTED_C6_BLOB = 'e3eeb820fa1826fb7ac29f3fce2fe0bdde8d564f'
EXPECTED_G11_BLOB = '970ccb164f8ab7d3de6681ff4af940b1638d1686'
PARENT_RESULT_COMMIT = '4090367131f0a4fac22cf13571f157cab0a284dc'

MATTER_NAMES = {
    'rho', 'rho_m', 'rho_b', 'density', 'matter', 'dust', 'current', 'j_m',
    'number_density', 'n_m', 'tmn', 'tmunu', 't_munu', 'stress_energy',
    'matter_action', 'dust_action', 'lag_m', 'lmatter', 'l_matter', 'v', 'w'
}
FORBIDDEN_COMPENSATORS = {
    'shell_force', 'a_drag', 'drag_force', 'artificial_pressure', 'pressure_floor',
    'viscosity', 'artificial_viscosity', 'poisson_force', 'gr_force', 'finite_eta'
}


def git_blob_sha1(data: bytes) -> str:
    hdr = f'blob {len(data)}\0'.encode()
    return hashlib.sha1(hdr + data).hexdigest()


def assigned_node(tree: ast.AST, name: str):
    for node in ast.walk(tree):
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for target in targets:
                if isinstance(target, ast.Name) and target.id == name:
                    return node.value
    return None


def unparse(node) -> str | None:
    return ast.unparse(node) if node is not None else None


def names_in(node) -> set[str]:
    if node is None:
        return set()
    return {x.id for x in ast.walk(node) if isinstance(x, ast.Name)}


def string_literals(tree: ast.AST) -> list[str]:
    return [x.value for x in ast.walk(tree) if isinstance(x, ast.Constant) and isinstance(x.value, str)]


def sympy_declared_names(tree: ast.AST) -> set[str]:
    out: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        f = node.func
        is_symbols = isinstance(f, ast.Attribute) and isinstance(f.value, ast.Name) and f.value.id == 'sp' and f.attr in {'symbols', 'Symbol'}
        if not is_symbols or not node.args:
            continue
        a0 = node.args[0]
        if isinstance(a0, ast.Constant) and isinstance(a0.value, str):
            out.update(a0.value.replace(',', ' ').split())
    return out


def find_assignment_text(tree: ast.AST, name: str) -> str | None:
    node = assigned_node(tree, name)
    return unparse(node)


def main() -> None:
    c6_bytes = C6.read_bytes()
    g11_bytes = G11.read_bytes()
    c6_blob = git_blob_sha1(c6_bytes)
    g11_blob = git_blob_sha1(g11_bytes)
    c6_src = c6_bytes.decode()
    g11_src = g11_bytes.decode()
    tree = ast.parse(c6_src)
    g11_tree = ast.parse(g11_src)

    lag_node = assigned_node(tree, 'lag')
    grav_node = assigned_node(tree, 'grav')
    aest_node = assigned_node(tree, 'aest')
    mem_node = assigned_node(tree, 'mem')
    fields_node = assigned_node(tree, 'fields')
    matter_node = assigned_node(tree, 'matter')
    matter_pass_node = assigned_node(tree, 'matter_pass')
    partials_node = assigned_node(tree, 'partials')

    lag_names = names_in(lag_node)
    declared = sympy_declared_names(tree)
    matter_declared = sorted(declared & MATTER_NAMES)
    matter_in_lag = sorted(lag_names & MATTER_NAMES)

    # Trace the variational construction mechanically: partials are generated by
    # sp.diff(lag, ...), then EL blocks are assembled from fparts. These source
    # snippets are reported, not interpreted through execution.
    diff_lag_calls = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
            if isinstance(node.func.value, ast.Name) and node.func.value.id == 'sp' and node.func.attr == 'diff':
                if node.args and isinstance(node.args[0], ast.Name) and node.args[0].id == 'lag':
                    diff_lag_calls.append(ast.unparse(node))

    el_loop_uses_fparts = False
    for node in ast.walk(tree):
        if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name) and node.value.id == 'fparts':
            el_loop_uses_fparts = True
            break

    matter_is_dict = isinstance(matter_node, ast.Dict)
    matter_pass_literal_true = isinstance(matter_pass_node, ast.Constant) and matter_pass_node.value is True
    matter_text = unparse(matter_node) or ''
    conservation_present = matter_is_dict and all(k in matter_text for k in ('continuity', 'geodesic'))

    # The audited action can generate matter stress-energy only if matter is
    # represented by an explicit action contribution / matter variable in lag.
    explicit_matter_action_present = bool(matter_in_lag or matter_declared)

    # Metric/lapse/shift blocks all derive from exactly the same lag expression.
    # If lag has no matter representation, these blocks cannot carry T_munu.
    variational_pipeline_from_lag = len(diff_lag_calls) >= 2 and el_loop_uses_fparts
    gravitational_source_dependence = explicit_matter_action_present and variational_pipeline_from_lag

    # Verify there is no hidden compensating phenomenology in executable names.
    executable_names = {n.id for n in ast.walk(tree) if isinstance(n, ast.Name)} | {n.id for n in ast.walk(g11_tree) if isinstance(n, ast.Name)}
    compensators_used = sorted(executable_names & FORBIDDEN_COMPENSATORS)
    no_hidden_compensator = len(compensators_used) == 0

    provenance_ok = (c6_blob == EXPECTED_C6_BLOB and g11_blob == EXPECTED_G11_BLOB)
    conservation_backreaction_consistent = conservation_present and explicit_matter_action_present and gravitational_source_dependence

    gates = {
        'B0_G1_provenance': provenance_ok,
        'B0_G2_variational_action_matter_inclusion': explicit_matter_action_present,
        'B0_G3_gravitational_source_dependence': gravitational_source_dependence,
        'B0_G4_conservation_backreaction_consistency': conservation_backreaction_consistent,
        'B0_G5_no_hidden_phenomenological_closure': no_hidden_compensator,
    }

    if all(gates.values()):
        classification = 'NL1C7B_MATTER_BACKREACTION_CLOSURE_AUDIT_PASS'
    elif provenance_ok and conservation_present and not explicit_matter_action_present and not gravitational_source_dependence and no_hidden_compensator:
        classification = 'NL1C7B_MATTER_BACKREACTION_CLOSURE_INCOMPLETE'
    else:
        classification = 'NL1C7B_MATTER_BACKREACTION_CLOSURE_FAIL'

    result = {
        'classification': classification,
        'scope': 'Frozen NL1C6 source audit only; no equation modification and no spherical trajectory.',
        'provenance': {
            'parent_nl1c7a_result_commit': PARENT_RESULT_COMMIT,
            'c6_source_blob_expected': EXPECTED_C6_BLOB,
            'c6_source_blob_actual': c6_blob,
            'g11_source_blob_expected': EXPECTED_G11_BLOB,
            'g11_source_blob_actual': g11_blob,
        },
        'source_evidence': {
            'lag_assignment': unparse(lag_node),
            'grav_assignment': unparse(grav_node),
            'aest_assignment': unparse(aest_node),
            'mem_assignment': unparse(mem_node),
            'fields_assignment': unparse(fields_node),
            'declared_sympy_names': sorted(declared),
            'matter_like_declared_sympy_names': matter_declared,
            'matter_like_names_in_lag': matter_in_lag,
            'lag_names': sorted(lag_names),
            'sp_diff_lag_calls': diff_lag_calls,
            'EL_pipeline_uses_fparts': el_loop_uses_fparts,
            'matter_assignment': matter_text,
            'matter_pass_assignment': unparse(matter_pass_node),
            'matter_pass_is_literal_true': matter_pass_literal_true,
            'conservation_geodesic_control_present': conservation_present,
            'forbidden_compensator_names_used': compensators_used,
        },
        'derived_findings': {
            'explicit_matter_action_or_variable_in_variational_lag': explicit_matter_action_present,
            'field_EL_pipeline_generated_from_lag': variational_pipeline_from_lag,
            'action_derived_matter_backreaction_in_gravitational_blocks': gravitational_source_dependence,
            'matter_conservation_control_is_separate': conservation_present and not explicit_matter_action_present,
            'existing_equations_sufficient_for_self_gravitating_overdensity': all(gates.values()),
        },
        'gates': gates,
        'continuation': (
            'If INCOMPLETE, preregister and derive a minimally coupled pressureless-matter variational closure '
            'before any NL1C7 eta=0 collapse/turnaround trajectory.'
        ),
        'claim_boundary': {
            'historical_C6_reclassified': False,
            'historical_C7A_reclassified': False,
            'nonlinear_evolution_executed': False,
            'finite_eta_executed': False,
        },
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + '\n')
    print(json.dumps(result, indent=2, sort_keys=True))

    # INCOMPLETE is an allowed scientific outcome, not a workflow error.
    raise SystemExit(0 if classification in {
        'NL1C7B_MATTER_BACKREACTION_CLOSURE_AUDIT_PASS',
        'NL1C7B_MATTER_BACKREACTION_CLOSURE_INCOMPLETE',
    } else 2)


if __name__ == '__main__':
    main()
